<a href="https://colab.research.google.com/github/mrinalinimurugan/Tensorflow-with-Keras/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Fundamental concepts of tensors using tensorflow

In [ ]:
#Introduction to tensors

In [ ]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimension of a tensor (ndim stands for umber of dimensons)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of a vector
vector.ndim

1

In [ ]:
#Create a matrix
matrix = tf.constant([[10,7],
                     [7,19]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 19]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) #Specify the data type with dtype parameter 

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#number of dimension of another_matrix
another_matrix.ndim

2

In [ ]:
#Creating tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Scalar:a single number
#vector:a no with direction
#matrix:a 2-dim array if nos
#tensor:a n-dim array of nos

In [ ]:
#Create tensor with tf.Variable

In [ ]:
tf .Variable

tensorflow.python.ops.variables.Variable

In [ ]:
#Create the same tensor as tf.Variable as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [ ]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Lets try change one of the elemenets in our changeable tensor
'''changeable_tensor[0] = 7
changeable_tensor'''

'changeable_tensor[0] = 7\nchangeable_tensor'

In [ ]:
#try.assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
'''unchangeable_tensor[0].assign(7)'''

'unchangeable_tensor[0].assign(7)'

In [ ]:
#Variable tensor : can change with assign function
#Constant tensor: cannot change tensor

In [ ]:
#Create random tensors:tensors of some arbitrary size which contains random nos
random_1 = tf.random.Generator.from_seed(42) #set seed for reproductibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproductibility
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2 #Act like random but not random

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#Shuffle the order of elements in a tensor-shuffle data so that inherent order doesnt affect learing
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
#shuffle a non shuffle tensor
tf.random.set_seed(42) #global level random seed : it will keep the order constant
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed : it will shuffle the order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#shuffle a non shuffle tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
#Other ways to make tensors
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Turn numpy array into tensors : the main difference bw numy arrays and tensors is that tensors can be run in GPU mushc faster
import numpy as np
numpy_a = np.arange(1,25,dtype = np.int32)
numpy_a

#x = tf.constant(some matrix) #capital for matrix or tensor
#y = tf.constant(vector) #non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_a, shape=(2,3,4))
B = tf.constant(numpy_a)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*4*3

24

In [ ]:
A.ndim

3

In [ ]:
#Getting info from tensors
#create a rank 4 tensor(4 dimension)
rank4tensor = tf.zeros(shape=[2,3,4,5])
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4tensor.shape,rank4tensor.ndim,tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element:",rank4tensor.dtype)
print("Number of dimensions(rank):",rank4tensor.ndim)
print("Elememts oalong the 0 axis:",rank4tensor.shape[0])
print("Elememts oalong the 1 axis:",rank4tensor.shape[-1])
print("Shape of tensor:",rank4tensor.shape)
print("Total no of elements in tensor",tf.size(rank4tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Elememts oalong the 0 axis: 2
Elememts oalong the 1 axis: 5
Shape of tensor: (2, 3, 4, 5)
Total no of elements in tensor 120


In [ ]:
#Indexing tensors 
#get first 2 elements
rank4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank4tensor[:1,:,:,:1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor(2 dim)
rank2tensor = tf.constant([[10,7],
             [3,4]])
rank2tensor.shape,rank2tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each row of our rank 2 tensor
rank2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add in extra dim to our rank 2 tensor
rank3tensor = rank2tensor[...,tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis 
tf.expand_dims(rank2tensor,axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
#Manipulating tensors or tensor operations
#BAsic operations
#Can add values to the tensors using the operator
tensor  = tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged
tensor =  tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  85],
       [ 65,  70]], dtype=int32)>

In [ ]:
tensor-150

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-130, -133],
       [-137, -136]], dtype=int32)>

In [ ]:
tensor/5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[4. , 3.4],
       [2.6, 2.8]])>

In [ ]:
#We can use the tensorflow built in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.add(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 22],
       [18, 19]], dtype=int32)>

In [ ]:
tf.subtract(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]], dtype=int32)>

In [ ]:
tf.divide(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[6.66666667, 5.66666667],
       [4.33333333, 4.66666667]])>

In [ ]:
#Matrix Multiplication
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor 
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
'''tf.matmul(x,y)'''

'tf.matmul(x,y)'

In [ ]:
tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.matmul(y,tf.reshape(x,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [ ]:
#can do same with transpose
x,tf.transpose(x),tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#matrix mul with transpose
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Dot product
#matrix mul is also referred to as  dot product
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#check the values of y and transposed y
print("Normal y:")
print(y,"\n")
print("y reshaped to (2,3):")
print(tf.reshape(y,shape=(2,3)))
print("\n")
print("y transposed:")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Create a new tensor with default datatype (float32)
b = tf.constant([1.7,7.4])
b.dtype

tf.float32

In [ ]:
c = tf.constant([1,7])
c.dtype

tf.int32

In [ ]:
#Change from float32 to float16 (reduced precision)
d = tf.cast(b,dtype=tf.float16)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
#int32 to float32
e=tf.cast(c,dtype=tf.float32)
e

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [ ]:
#Aggregating tensors(collection):condensing them from multiple values down to a smaller amount of values
#Getting the absolute values
d = tf.constant([-7,-10])
d


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Get the absolute value
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#get the minimun,max,mean,sum
tf.math.reduce_max(d)


<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
tf.math.reduce_mean(d)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [ ]:
tf.math.reduce_min(d)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [ ]:
tf.math.reduce_sum(d)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [ ]:
tf.reduce_prod(d)

<tf.Tensor: shape=(), dtype=int32, numpy=70>

In [ ]:
m = tf.constant(np.random.randint(0,100,size=50))
m

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 54, 94, 17, 26, 62, 92, 10, 19, 27, 48, 57, 67, 57, 74, 30, 93,
       35, 51, 13, 49, 19, 95, 78, 82, 44, 85, 81, 59, 60, 79, 28, 82, 62,
       79, 96, 51, 19, 24,  1, 34, 68, 91, 51, 20, 42, 91, 73, 78,  6])>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(m)

<tf.Tensor: shape=(), dtype=int64, numpy=799>

In [ ]:
tfp.stats.stddev(tf.cast(m,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.281189>

In [ ]:
tf.math.reduce_std(tf.cast(m,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.281189>

In [ ]:
#Find the positional maximum and minimum
#Create a new tensor 
tf.random.set_seed(42)
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
f[tf.argmax(f)]==tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
#Squeezing a tensor(removing all single dimension)
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeeze=tf.squeeze(g)
g_squeeze #Removes all the one dimensions

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#One hot encoding
#Create a list of indices
l = [0,1,2,3] #red,green,blue,purple
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(l, depth=4 , on_value="yo i love dl", off_value="i like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love dl', b'i like to dance', b'i like to dance',
        b'i like to dance'],
       [b'i like to dance', b'yo i love dl', b'i like to dance',
        b'i like to dance'],
       [b'i like to dance', b'i like to dance', b'yo i love dl',
        b'i like to dance'],
       [b'i like to dance', b'i like to dance', b'i like to dance',
        b'yo i love dl']], dtype=object)>

In [ ]:
#Squaring ,log,square root
#Create a new tensor
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
#Tensors and numpy
j=tf.constant(np.array([3.,7.,10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert back to numpy
np.array(j),type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor j to a nump array
j.numpy(),type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
j=tf.constant([3.])
j.numpy()[0]

3.0

In [ ]:
#Default types of each are slightly diff
numpy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])
numpy_j.dtype,tensor_j.dtype

(tf.float64, tf.float32)

In [ ]:
#Finding the access to GPUs
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Jul 24 06:54:48 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------